### ISSUE TITLE
bug: Crashing unexpected token .

### ISSUE THREAD

**Issue by NicolasCastroGarcia** [vime-js/vime#157]
Bug Report

Vime version: 5.0.27 (core/react)

**Current behavior:**

Crashes with the following error:

`
SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/node_modules/@vime/core/dist/cjs/index.cjs.js:7:31)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
/node_modules/@vime/core/dist/cjs/withComponentRegistry-50d191fe.js:33
        onFail?.();
               ^
`

I was using 5.0.19 before, and updated to latest. Sadly, this error ocurred, and I haven't changed anything other than de package version. 

Any solutions or help would be appreciated.

Thank you.

**Comment by Enigma10** [comment]
I am also getting this error for my next js project after updating to the latest version

**Comment by mihar-22** [comment]
For now roll back to the version where it was working and I'll get to this once I have some time. I'm not sure why TypeScript stopped transpiling optional chaining syntax.

**Comment by vin-ni** [comment]
I'm also getting this error

**Comment by MaxChu23** [comment]
Having the same issue running with nodejs:

```javascript
Server Error
SyntaxError: Unexpected token '.'

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
<unknown>
/node_modules/ (vime/core/dist/cjs/withComponentRegistry-50d191fe.js (33)
```

**Comment by brantchoate** [comment]
is this repo maintained? Only asking because it seems strange to have the React version not working for this long

**Comment by marcelfahle** [comment]
Try using node14+ for building.

**Comment by NicolasCastroGarcia** [comment]
> Try using node14+ for building.

This fixed it for me. Thank you very much @marcelfahle 

New bugs are present in the lastest React version though, so I will open the respective issues. 

Thank you
