### ISSUE TITLE
bug: support node16

### ISSUE THREAD

**Issue by winsa24** [vime-js/vime#217]
# Bug Report

**Vime version:**  "@vime/react": "^5.0.31"

**Current behavior:**
When I try to import vime in my react project, I got the following error: 
```
TypeError: Failed to execute 'define' on 'CustomElementRegistry': parameter 2 is not a function
      at Object.exports.convert (node_modules/jsdom/lib/jsdom/living/generated/CustomElementConstructor.js:8:11)
      at CustomElementRegistry.define (node_modules/jsdom/lib/jsdom/living/generated/CustomElementRegistry.js:120:43)
      at Object.define (node_modules/@vime/react/src/lib.tsx:17:20)
      at Object.<anonymous> (node_modules/@vime/react/src/components/Audio.tsx:17:1)
      at Object.<anonymous> (node_modules/@vime/react/src/components/index.ts:4:1)
```
It might failed with no supporting node version 16.

**Expected behavior:**
Support node16.

**Comment by chovy** [comment]
This project looks dead to me. Nobody in discord, no respone on tickets in months.

**Comment by rossng** [comment]
I don't think this is an issue with the Node version. Vime relies on various Web Component APIs like [custom elements](https://caniuse.com/custom-elementsv1).

It's hard to know exactly what's happening, but I suspect the build pipeline for your project is either injecting a broken polyfill (that's what jsdom provides) or is transpiling code in a way that doesn't work with custom elements.

Can you share the details of how you're building your React project?

**Comment by austinfox** [comment]
I'm experiencing this issue as well. I added some logging in lib.jsx in the "define" function (where customElements.define is being called). I logged `typeof clazz` and its returning undefined. This only appears to happen when running Jest tests (JSDom environment). JSDom is the one actually throwing the error here, but I believe something is wrong with Vime since `clazz` is undefined in the Vime code.

**Comment by austinfox** [comment]
I believe I've discovered the issue. I added a lot of logging and found that in the generated javascript in dist/cjs/components, the imported vime core`require('@vime/core`) doesn't have any of the components attached to the resolved value. For example, take a look here:

https://unpkg.com/browse/@vime/react@5.3.1/dist/cjs/components/Audio.jsx

I added logging for `core_1`, and it returns a real value corresponding to the core code, but `core_1.VmAudio` and `core_1.VmFile` are undefined. Then `define` is called with undefined value and JSDom recognizes that the provided param is not a function as it expects, and ultimately throws an error.

**Comment by sampaioxsamuel** [comment]
any updates on this?
