### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'trim')

### ISSUE THREAD

**Issue by nick4414** [vime-js/vime#379]
Hi,
since the 10.01.2024 all our users get the bug:

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'trim')
    at Object.buildAbsoluteURL (url-toolkit.js:21:33)
    at e.loadSource (hls.ts:401:39)
    at HLS.<anonymous> (video-player~user-account.js?id=fd885bb62350cccedb83:82493:65)
    at Generator.next (<anonymous>)
    at video-player~user-account.js?id=fd885bb62350cccedb83:82360:67
    at new Promise (<anonymous>)
    at push../node_modules/@vime/core/dist/custom-elements/index.js.__awaiter$f (video-player~user-account.js?id=fd885bb62350cccedb83:82346:10)
    at HLS.onSrcChange (video-player~user-account.js?id=fd885bb62350cccedb83:82490:12)
    at t.<anonymous> (video-player~user-account.js?id=fd885bb62350cccedb83:82413:16)
    at o.emit (index.js:203:33)

when using the HLS Player. I didn't change the code for months.
There was a Chrome, Edge, Safari Update on the 10.01.24 and that's when the errors started. Could it be a problem on your end ?

EDIT:
Your HLS demo has the same issue:
https://vimejs.com/demo

**Comment by ashveen** [comment]
Looks related to hls.js v1.5.x released 2 days ago.
https://github.com/video-dev/hls.js/releases/tag/v1.5.0

I added to version="1.4.14" as workaround in the <Hls> props to mitigate this issue.
Been going through the hls.js release notes and so far have not found any clue why it is breaking.

**Comment by BBR-Agency** [comment]
> Hi, since the 10.01.2024 all our users get the bug:
> 
> Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'trim') at Object.buildAbsoluteURL (url-toolkit.js:21:33) at e.loadSource (hls.ts:401:39) at HLS. (video-player~user-account.js?id=fd885bb62350cccedb83:82493:65) at Generator.next () at video-player~user-account.js?id=fd885bb62350cccedb83:82360:67 at new Promise () at push../node_modules/@vime/core/dist/custom-elements/index.js.__awaiter$f (video-player~user-account.js?id=fd885bb62350cccedb83:82346:10) at HLS.onSrcChange (video-player~user-account.js?id=fd885bb62350cccedb83:82490:12) at t. (video-player~user-account.js?id=fd885bb62350cccedb83:82413:16) at o.emit (index.js:203:33)
> 
> when using the HLS Player. I didn't change the code for months. There was a Chrome, Edge, Safari Update on the 10.01.24 and that's when the errors started. Could it be a problem on your end ?
> 
> EDIT: Your HLS demo has the same issue: https://vimejs.com/demo

did you by any chance get a workaround on this? especially  on  **hls videos**?

**Comment by nick4414** [comment]
A workaround is (like @ashveen mentioned):

```
<template>
  <Player controls>
    <Hls :config="hlsConfig" **version="1.4.14"** poster="/media/poster.png">
      <source data-src="/media/index.m3u8" type="application/x-mpegURL" />
    </Hls>
    <!-- ... -->
  </Player>
</template>
```

**Comment by sheerazabbas** [comment]
Thanks for the quick workaround @ashveen

**Comment by Tayyab-Abbas** [comment]
> Hi, since the 10.01.2024 all our users get the bug:
> 
> Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'trim') at Object.buildAbsoluteURL (url-toolkit.js:21:33) at e.loadSource (hls.ts:401:39) at HLS. (video-player~user-account.js?id=fd885bb62350cccedb83:82493:65) at Generator.next () at video-player~user-account.js?id=fd885bb62350cccedb83:82360:67 at new Promise () at push../node_modules/@vime/core/dist/custom-elements/index.js.__awaiter$f (video-player~user-account.js?id=fd885bb62350cccedb83:82346:10) at HLS.onSrcChange (video-player~user-account.js?id=fd885bb62350cccedb83:82490:12) at t. (video-player~user-account.js?id=fd885bb62350cccedb83:82413:16) at o.emit (index.js:203:33)
> 
> when using the HLS Player. I didn't change the code for months. There was a Chrome, Edge, Safari Update on the 10.01.24 and that's when the errors started. Could it be a problem on your end ?
> 
> EDIT: Your HLS demo has the same issue: https://vimejs.com/demo

Yeah, that seems to be a bad implementation in @vime/vue for using dependencies with cdn @mihar-22, I know this is not actually your package fault but in case if you use all other dependencies with their cdn. they will get updated from time to time even with bugs that what users currently face even they don't have updated their package. As you guys are going toward #Vidtack package. Please keep in mind that you should use dependencies as module part of your package not as cdn So, your package could be stable till every update you launch.
Thanks

**Comment by sven-ra** [comment]
Downgrading HLS to 1.4.14 does not fix the issue on Safari. On desktop Safari half the times it works other half not.
On iOS Safari I get the same error every time.

**Comment by zshall** [comment]
![image](https://github.com/user-attachments/assets/b03442a2-aa34-457b-932c-293299d027bf)

On Safari this seems to be related to how sources are used. In Chrome the actual m3u8 URL with type `application/x-mpegURL` is used but in Safari an object URL is used with type `video/mp4`. The code that's failing is looking for either a source ending in `m3u8` or a source with `application/x-mpegURL` type and it isn't finding either of them. I'm trying to figure out whether this is an HLS.js problem or a Vime problem since the HLS.js demo works fine on their website in Safari.

**Comment by zshall** [comment]
I've turned on debug logs in HLS.js in Safari and collected this one: `[error] >"Media element src was set while attaching MediaSource (blob:http://localhost:5173/7f520dde-4d88-4b5d-bfc8-9c340d5bcc3a > undefined)"`

Tracking it down I've noticed HLS.js sets an object URL and changes the `source` element. https://github.com/video-dev/hls.js/blob/c21f4bf863968283ab26afe460c070d05166a4f9/src/controller/buffer-controller.ts#L241

This fires the `emptied` event on the `video` element and produces that logging error. Now the src is undefined, which triggers `onSrcChange` in Vime it appears. https://github.com/vime-js/vime/blob/c1f311950c52b5c49329873a6bb9739f3727223f/packages/core/src/components/providers/hls/hls.tsx#L239

![image](https://github.com/user-attachments/assets/8999cf28-d5b6-4f45-81c1-0f3efe605afd)

This listener is called with the `m3u8` URL when the page loads:

![image](https://github.com/user-attachments/assets/732cd022-ed89-477d-bc68-e7157d4f1426)

And then again after the element was replaced with `undefined`.

This appears to be happening right here: https://github.com/vime-js/vime/blob/c1f311950c52b5c49329873a6bb9739f3727223f/packages/core/src/components/providers/hls/hls.tsx#L128 the `onSrcChanged` event fires when `get src()` returns something else. It's returning nothing since it only looks for `m3u8` or the mpeg content type. Either way it doesn't find it and the `loadSource` function is called again with `undefined`.

Investigating fixes; I'm not familiar with Vime's build pipeline but it seems like this could be the hotspot to focus on.

**Comment by zshall** [comment]
I've put together a change that seems to have fixed the problem; a cache has been added to the HLS source URL that will return if it ends up getting set. That way if HLS.js sets the URL to an object URL it won't try to load the new `blob:` URL or `undefined` and will return the old URL, which prevents the bug.
