### ISSUE TITLE
Support Vue 3

### ISSUE THREAD

**Issue by snowdream** [vime-js/vime#92]
vite: https://github.com/vitejs/vite
create-vite-app: https://github.com/vitejs/create-vite-app

```
➜  ui git:(master) ✗ npm run dev

> ui@0.0.0 dev /project
> vite

vite v1.0.0-rc.4
[vite] Optimizable dependencies detected:
@vime/vue, vue

[vite] Dep optimization failed with error:
'default' is not exported by node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js, imported by node_modules/@vime/vue/dist/esm/components.js
Error: 'default' is not exported by node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js, imported by node_modules/@vime/vue/dist/esm/components.js
    at error (/project/node_modules/rollup/dist/shared/rollup.js:5210:30)
    at Module.error (/project/node_modules/rollup/dist/shared/rollup.js:9725:16)
    at handleMissingExport (/project/node_modules/rollup/dist/shared/rollup.js:9647:28)
    at Module.traceVariable (/project/node_modules/rollup/dist/shared/rollup.js:10120:24)
    at ModuleScope.findVariable (/project/node_modules/rollup/dist/shared/rollup.js:8679:39)
    at MemberExpression.bind (/project/node_modules/rollup/dist/shared/rollup.js:6383:49)
    at AssignmentExpression.bind (/project/node_modules/rollup/dist/shared/rollup.js:2844:23)
    at ExpressionStatement$1.bind (/project/node_modules/rollup/dist/shared/rollup.js:2844:23)
    at Program$1.bind (/project/node_modules/rollup/dist/shared/rollup.js:2840:31)
    at Module.bindReferences (/project/node_modules/rollup/dist/shared/rollup.js:9721:18) {
  code: 'MISSING_EXPORT',
  url: 'https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module',
  id: '/project/node_modules/@vime/vue/dist/esm/components.js',
  pos: 82,
  loc: {
    file: '/project/node_modules/@vime/vue/dist/esm/components.js',
    line: 4,
    column: 7
  },
  frame: '2: /* tslint:disable */\n' +
    '3: /* auto-generated vue proxies */\n' +
    "4: import Vue from 'vue';\n" +
    '          ^\n' +
    "5: import { createCommonRender, createCommonMethod } from './vue-component-lib/utils';\n" +
    '6: const customElementTags = [',
  watchFiles: [
    '/project/node_modules/vue/dist/vue.runtime.esm-bundler.js',
    '/project/node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js',
    '/project/node_modules/@vime/vue/dist/esm/index.js',
    '/project/node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js',
    '/project/node_modules/@vue/runtime-core/node_modules/@vue/shared/dist/shared.esm-bundler.js',
    '/project/node_modules/@vue/reactivity/dist/reactivity.esm-bundler.js',
    '/project/node_modules/@vime/vue/dist/esm/components.js',
    '/project/node_modules/@vime/vue/dist/esm/mixins.js',
    '/project/node_modules/@vime/core/dist/index.js',
    '/project/node_modules/@vime/core/loader/index.js',
    '/project/node_modules/@vime/vue/dist/esm/vue-component-lib/utils.js',
    '/project/node_modules/@vime/core/dist/esm/index.js',
    '/project/node_modules/@vime/core/dist/esm/loader.js',
    '/project/node_modules/@vime/core/dist/esm/polyfills/index.js',
    '/project/node_modules/@vime/core/dist/esm/PlayerDispatcher-d997c4cd.js',
    '/project/node_modules/@vime/core/dist/esm/index-1a670dd0.js',
    '/project/node_modules/@vime/core/dist/esm/PlayerProps-5f815c1e.js',
    '/project/node_modules/@vime/core/dist/esm/PlayerEvents-c5e0a046.js',
    '/project/node_modules/@vime/core/dist/esm/PlayerContext-f765b362.js',
    '/project/node_modules/@vime/core/dist/esm/dom-6e291ce0.js',
    '/project/node_modules/@vime/core/dist/esm/unit-f81589b4.js',
    '/project/node_modules/@vime/core/dist/esm/MediaType-aec4c150.js',
    '/project/node_modules/@vime/core/dist/esm/support-fbd84e26.js',
    '/project/node_modules/@vime/core/dist/esm/ViewType-6da43616.js',
    '/project/node_modules/@vime/core/dist/esm/network-1a639520.js',
    '/project/node_modules/@vime/core/dist/esm/polyfills/dom.js',
    '/project/node_modules/@vime/core/dist/esm/polyfills/core-js.js',
    '\u0000commonjsHelpers.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ui@0.0.0 dev: `vite`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ui@0.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/snowdream/.npm/_logs/2020-10-12T03_58_54_085Z-debug.log
```

**Comment by mihar-22** [comment]
Hey @snowdream Vue 3 is not supported just yet (only Vue 2), I'll try to add support for it soon.

**Comment by snowdream** [comment]
Thank you very much.


发自我的iPhone
